/***@licence*Copyright2014ATInternet,AllRightsReserved.*ATInternetTag4.5.4*/window.Xtconf={xt1:'.morbihan.gouv.fr',xtLogDom:'.xiti.com/hit.xiti',xtfirst:false,xt2:'0',xt3:3650,xt4sec:'20',xt4rss:'20',xt4epr:'20',xt4erec:'20',xt4adi:'20',xt4adc:'20',xt4al:'20',xtsds:'https://logs1241',xtsd:'http://logi241',xtsts:0,xtsite:function(x){return x+ xt8},xtscript:'',xtpreview:false,xtnocookies:false,xtcode:'',xt46:'1',xt50:'1',xt48:'',xt54:false,xt58:false,xtdocl:false,xttredir:500,xtkwv:'xtmc',xtkwp:'xtnp'};
window.Xtcore=function(){function h(c){return"undefined"!==typeof c}function H(c){var a=typeof c;if("object"!==a||null===c)return"string"===a&&(c=encodeURIComponent('"'+c+'"')),String(c);var f,b,d=[],k=c&&c.constructor==Array;for(f in c)b=c[f],a=typeof b,c.hasOwnProperty(f)&&"function"!==a&&("string"===a?b=encodeURIComponent('"'+b.replace(/[^\\]"/g,'\\"')+'"'):"object"===a&&null!==b&&(b=H(b)),d.push((k?"":encodeURIComponent('"'+f+'":'))+String(b)));return(k?"[":"{")+String(d)+(k?"]":"}")}function oa(c){return c.replace(/%3C/g,
"<").replace(/%3E/g,">").replace(/[<>]/g,"")}function l(c,a,f,b,d){a=0===d?a:encodeURIComponent(a);pa||(j.cookie=c+"="+a+";expires="+f.toGMTString()+";path=/"+b)}function g(c,e,f){var b;try{b=T.location.href}catch(d){b=a.location.href}e=null===e||!h(e)?oa(b.toLowerCase().replace(/%3d/g,"=")):e;if(0<e.indexOf(c+"=")){e=e.substr(1);c=e.substr(e.indexOf(c+"="));if(2!=f){if(1!=f)try{c=decodeURIComponent(c)}catch(k){c=unescape(c)}if(e=c.match(/(\[[^\]]*\])/g)){b="";for(var r=0,m=e.length;r<m;r++)b=e[r].substring(1,
e[r].length-1),c=c.replace(b,encodeURIComponent(b))}}e=c.indexOf("#");b=c.search(/&.[^&]+=/gi);b=-1==b?-1==e?c.length:e:0<e&&e<b?e:b;return 1==f?decodeURIComponent(c.substring(c.indexOf("=")+1,b)):2==f?c.substring(c.indexOf("=")+1,b):c.substring(c.indexOf("=")+1,b).replace("&","%26")}return null}function D(c,a,f,b){if((0===qa||3==qa||"C"!=c)&&"P"!=c)Xa&&"0"==aa&&"F"==c?(w=w.replace("&p="+g("p",w,2),""),w=w.replace("&s2="+g("s2",w),""),AT_hit.isPreviewOrPrerendering()||AT_hit.sendTag(c,null,null,a),
Xa=!1):AT_hit.sendTag(c,a);null!==f&&(h(f)&&"M"!=c)&&(""===b||null===b?j.location=f:window.open(f,"xfen","").focus())}function E(c){c-=100*Math.floor(c/100);return 10>c?"0"+c:c}function U(c){return Math.floor(Math.random()*Math.pow(10,c))}var ra=this;ra.sentHits=[];var n=Xtconf.xt1,Ya=Xtconf.xtscript,Za=window.xtLogDom=Xtconf.xtLogDom,wb=Xtconf.xtpreview,$a=Xtconf.xtfirst,pa=Xtconf.xtnocookies,ab=Xtconf.xtcode,aa=Xtconf.xt46,sa=Xtconf.xt50,bb=Xtconf.xt48,xb=Xtconf.xt54,yb=Xtconf.xt58,zb=Xtconf.xtdocl,
Ab=Xtconf.xt2,Bb=Xtconf.xt3;window.xttredir=Xtconf.xttredir;var cb=Xtconf.xtkwv,db=Xtconf.xtkwp,ta=[],A=[];A.sec=Xtconf.xt4sec;A.rss=Xtconf.xt4rss;A.epr=Xtconf.xt4epr;A.erec=Xtconf.xt4erec;A.adi=Xtconf.xt4adi;A.adc=Xtconf.xt4adc;A.al=Xtconf.xt4al;A.es=Xtconf.xt4epr;A.ad=Xtconf.xt4adi;var ua=[],Xa=!0,O=!1,va=null,a=window.xw=window,j=window.xd=document,t=navigator,Cb=window.xtv=h(a.xtczv)?"4.5.4-"+a.xtczv:"4.5.4",n=window.xt1=h(a.xtdmc)?";domain="+a.xtdmc:""!==n?";domain="+n:"",T=h(a.xtnv)?
a.xtnv:j,Db=window.xt7=h(a.xtsdi)?a.xtsdi:h(a.xtsd)?a.xtsd+Za:("https:"===j.location.protocol?Xtconf.xtsds:Xtconf.xtsd)+Za,ba=h(a.xtsts)?a.xtsts:Xtconf.xtsts,ca="";if(xb){var wa="";try{wa=T.location.href}catch(ac){wa=a.location.href}var Eb=/#.*/,xa=null;try{xa=wa.match(Eb)[0]}catch(bc){xa=null}ca=(ca=xa)?"&sta="+encodeURIComponent(oa(ca)):""}var eb=h(a.xtcustom)?H(a.xtcustom):"",I=window.xt8=h(a.xtsite)?a.xtsite:0,Fb=window.xt9=h(a.xtn2)?"&s2="+a.xtn2:"",Gb=window.xt8b=(0===I?"":"s="+I)+(0===ba?"":
0===I?"sts="+ba:"&sts="+ba),J=window.xtp=h(a.xtpage)?a.xtpage:"",fb=h(a.xto_force)?a.xto_force.toLowerCase():null,L="redirect"===I,Hb=a.xtdi?"&di="+a.xtdi:"",Ib=a.xtidp?"&idpays="+a.xtidp:"",Jb=a.xtidprov?"&idprov="+a.xtidprov:"",p=h(a.xtparam)?a.xtparam:"",aa=h(a.xtnopage)&&"1"===a.xtnopage?"0":aa,sa=h(a.xtergo)&&"0"===a.xtergo?"0":sa,qa=h(a.scriptOnClickZone)&&"1"===sa?a.scriptOnClickZone:0;h(a.xt_orderid);h(a.xtidcart);var Kb=""!==ab?"&code="+ab:"",ya=[],da=[],V=[],ea=[],za=[],M=[];window.xt44=
h(a.xtprod_load)?"&pdtl="+a.xtprod_load:"";a.addEventListener?a.addEventListener("unload",function(){},!1):a.attachEvent&&a.attachEvent("onunload",function(){});j.addEventListener?(j.addEventListener("keydown",function(){O=!0},!1),j.addEventListener("keyup",function(){O=!1},!1)):j.attachEvent&&(j.attachEvent("onkeydown",function(){O=!0}),j.attachEvent("onkeyup",function(){O=!1}));var Lb=a.roimt&&0>p.indexOf("&roimt",0)?"&roimt="+a.roimt:"",Mb=0>p.indexOf("&mc=",0)?a.xtmc?"&mc="+a.xtmc:g(cb)?"&mc="+
g(cb):g("xtmc")?"&mc="+g("xtmc"):"":"",Nb=g("xtcr")?"&mcrg="+g("xtcr"):"",Ob=a.xtac&&0>p.indexOf("&ac=",0)?"&ac="+a.xtac:"",Pb=a.xtat&&0>p.indexOf("&at=",0)?"&at="+a.xtat:"",gb=a.xtan&&0>p.indexOf("&an=",0)?"&an="+a.xtan:"",Qb=0>p.indexOf("&np=",0)?a.xtnp?"&np="+a.xtnp:g(db)?"&np="+g(db):g("xtnp")?"&np="+g("xtnp"):"":"",Rb=h(a.xtprm)&&0>p.indexOf("&x",0)?a.xtprm:"",p=p+(Lb+Mb+Nb+Ob+(""!==gb?gb:Pb)+Qb+Rb+ca),Aa="";try{Aa=top.document.referrer}catch(cc){try{Aa=T.referrer}catch(dc){}}var fa=screen,v=
window.xt21=new Date,hb=v.getTime()/36E5,q=window.xtf1=function(c,a){if(pa)return null;a=null!==a&&h(a)?a:"0";var f=RegExp("(?:^| )"+c+"=([^;]+)").exec(j.cookie)||null;f&&(f=oa(f[1]),"1"!=a&&(f=decodeURIComponent(f)));return f};window.xt_addchain=function(c,a){var f=a?a:"abmv",b=!ta[f]?0:ta[f];b++;p+="&"+f+""+b+"="+c;ta[f]=b};"function"===typeof xt_adch&&xt_adch();window.wck=l;window.xtf3=g;window.xt_mvt=function(c,a,f,b,d){if(b)for(var k=1;k<b.length+1;k++)f+="&"+(d?d:"abmv")+k+"="+b[k-1];D("","&p="+
c+"&s2="+a+"&abmvc="+f+"&type=mvt")};window.xt_med=function(c,a,f,b,d,k,r,m){b="F"==c&&(null===b||!h(b))?"":"M"==c?"&a="+b+"&m1="+d+"&m2="+k+"&m3="+r+"&m4="+m:"&clic="+b+(r?"&stc="+H(r):"");D(c,"&s2="+a+"&p="+f+b,d,k)};if($a=window.xtfirst=-1!=t.userAgent.indexOf("Safari")&&0>t.userAgent.indexOf("Chrome")||-1!=t.userAgent.indexOf("iPhone")||-1!=t.userAgent.indexOf("iPod")||-1!=t.userAgent.indexOf("iPad")||$a||a.xtidc||pa){var F=h(a.xtidc)?a.xtidc:q("xtidc"),G;null===F&&(F=Math.floor(999999*Math.random()),
G=v.getYear(),100>G&&(G+=2E3),100<G&&2E3>G&&(G+=1900),F=E(G)+""+E(v.getMonth())+""+E(v.getDate())+""+E(v.getHours())+""+E(v.getMinutes())+""+E(v.getSeconds())+""+F);var Ba=new Date;Ba.setTime(Ba.getTime()+31536E7);l("xtidc",F,Ba,n,1);var ib=q("xtidc"),F=F+(!a.xtidc&&(null===ib||ib!=F)?"-NO":"")}window.xt_ad=function(c,e,f,b){D("AT","&atc="+c+"&type=AT&patc="+J+"&s2atc="+a.xtn2+(b?"&stc="+H(b):""),e,f)};window.xt_adi=function(c,a,f){D("AT","&ati="+c+"&type=AT",a,f)};window.xt_adc=function(c,e,f,b,
d){D("AT","&atc="+e+"&type=AT&patc="+J+"&s2atc="+a.xtn2+(d?"&stc="+H(d):""));return AT_click.do_navig(c,f,b?"_blank":null,!0)};window.xt_click=function(c,a,f,b,d,k,r,m){d="F"==a&&(null===d||!h(d))?"":"&clic="+d+(m?"&stc="+H(m):"");D(a,"&s2="+f+"&p="+b+d);return AT_click.do_navig(c,k,r?"_blank":null,!0)};window.xt_form=function(c,a,f,b,d,k,r){d="F"==a&&(null===d||!h(d))?"":"&clic="+d+(r?"&stc="+H(r):"");D(a,"&s2="+f+"&p="+b+d);return AT_click.do_submit(c,!0,k)};window.xt_rm=function(c,e,f,b,d,k,r,
m,jb,h,g,l,n,j){d="&p="+f+"&s2="+e+"&type="+c+"&a="+b+"&m5="+g+"&m6="+l+(null!==d&&"0"!=d?"&"+d:"")+(null!==r&&"pause"!=b&&"stop"!=b?"&m1="+r+"&"+m+"&m3="+jb+"&m4="+h+"&m7="+n+"&m8="+j+"&prich="+J+"&s2rich="+a.xtn2:"")+(null!==k&&"0"!=k&&null!==r?"&rfsh="+k:"")+"&rn="+U(10);D(c,d);d=new Date;if(null!==k&&"0"!=k&&("play"==b||"play&buf=1"==b||"refresh"==b)){M[c]&&18E5<d.getTime()-M[c]&&(V[c]=0);if(("play"==b||"play&buf=1"==b)&&!V[c])V[c]=d.getTime()/1E3,ea[c]=parseInt(r),b=Math.floor(k),b=1500<b?1500:
5>b?5:b,ya[c]=b,da[c]=b,M[c]=!1;else if("refresh"==b&&("live"==l||!ea[c]||300<ea[c]&&2>100*ya[c]/ea[c]))b=M[c]?za[c]:d.getTime()/1E3-V[c],5>100*da[c]/(b+30)&&(da[c]=5*((b+30)/100)),M[c]&&(M[c]=!1,V[c]=d.getTime()/1E3-za[c]),za[c]=b;ua[c]=a.setTimeout("xt_rm('"+c+"','"+e+"','"+f+"','refresh','0','"+k+"',null,'"+m+"','"+jb+"','"+h+"','"+g+"','"+l+"')",1E3*da[c])}else if(("pause"==b||"stop"==b)&&null!==ua)a.clearTimeout(ua[c]),"stop"==b?ya[c]=0:M[c]=d.getTime()};var Ca=window.xtidpg=E(v.getHours())+
""+E(v.getMinutes())+""+E(v.getSeconds())+""+U(7),u=0,kb=0;window.xt16="";window.xt_addProduct=function(c,e,f,b,d,k){u++;a.xt16+="&pdt"+u+"=";a.xt16+=c?c+"::":"";a.xt16+=e?e:"";a.xt16+=f?"&qte"+u+"="+f:"";a.xt16+=b?"&mt"+u+"="+b:"";a.xt16+=d?"&dsc"+u+"="+d:"";a.xt16+=k?"&pcode"+u+"="+k:""};window.xt_rd=U;window.xt_addProduct_v2=function(c,e,f,b,d,k,r,m,h){u++;a.xt16+="&pdt"+u+"=";a.xt16+=c?c+"::":"";a.xt16+=e?e:"";a.xt16+=f?"&qte"+u+"="+f:"";a.xt16+=b?"&mt"+u+"="+b:"";a.xt16+=d?"&mtht"+u+"="+d:"";
a.xt16+=k?"&dsc"+u+"="+k:"";a.xt16+=r?"&dscht"+u+"="+r:"";a.xt16+=h?"&roimt"+u+"="+h:"";a.xt16+=m?"&pcode"+u+"="+m:""};window.xt_addProduct_load=function(c,e,f){e&&(kb++,a.xt44+=1==kb?"&pdtl=":"|",a.xt44+=c?c+"::":"",a.xt44+=e,a.xt44+=f?";"+f:"")};"function"==typeof xt_cart?xt_cart():a.xt16="";window.xt_ParseUrl=function(c,a,f){AT_hit.sendTag(f?"F":"old",a)};window.xt_ParseUrl3=function(c,a,f,b,d){AT_hit.sendTag("&ati="==d?"AT":"PDT",a,null,"&type="+("&ati="==d?"AT":"PDT"))};window.AT_click={id:0,
objs:[],elem:function(a,e,f,b,d,k,r,m){var g={};g.urlDest=d;g.type=a;g.n2=e;g.label=f;g.typeClick=b;g.target=k;g.submit=!1!==d;g.redir=!h(r)?!0:r;g.xtcust=h(m)?"&stc="+H(m):"";return g},addListener:function(a,e,f){window.addEventListener?a.addEventListener(e,f,!1):window.attachEvent&&a.attachEvent("on"+e,f)},tag:function(a,e,f,b,d,k,g,m,h){if(a&&"function"==typeof a.setAttribute)this.addElem(a,e,f,b,d,k,g,m,h);else if("object"==typeof a)for(var l in a)a.hasOwnProperty(l)&&"function"==typeof a[l].setAttribute&&
this.addElem(a[l],e,f,b,d,k,g,m,h)},addElem:function(a,e,f,b,d,k,g,m,h){this.id++;a.setAttribute("data-xtclickid",this.id);this.objs[this.id]=this.elem(e,f,b,d,k,g,m,h);"FORM"!=a.nodeName?this.addListener(a,"click",this.on_click_submit):this.addListener(a,"submit",this.on_click_submit)},on_click_submit:function(a){try{var e=a.target||a.srcElement,f=e.getAttribute("data-xtclickid"),b={},d="",k=a.defaultPrevented,g=window.AT_click;if(!f)for(var h=e.parentNode;h;){if(h.getAttribute("data-xtclickid")){f=
h.getAttribute("data-xtclickid");break}h=h.parentNode}f&&(b=g.objs[f],"AT"!=b.type?d+="&p="+b.label+("C"==b.type?"&clic="+b.typeClick+b.xtcust:""):"AT"==b.type&&(d+="&type=AT&atc="+b.label+b.xtcust),D(b.type,"&s2="+b.n2+d),!k&&b.redir&&(a.preventDefault(),"FORM"!=e.nodeName?g.do_navig(e,b.urlDest,b.target):g.do_submit(e,null,b.submit)))}catch(l){}},do_navig:function(c,e,f,b){var d=null;if("A"!=c.nodeName)for(var g=c.parentNode;g;){if("A"==g.nodeName){d=g;break}g=g.parentNode}else d=c;if(d){if(d.target=
f||c.target||"_self",d.href=e||c.href||d.href,!b||b&&!O)if(0>d.href.indexOf("mailto:"))if("_self"==d.target.toLowerCase()){if(setTimeout('self.location.href="'+d.href+'"',a.xttredir),b)return!1}else if("_top"==d.target.toLowerCase()){if(setTimeout('top.location.href="'+d.href+'"',a.xttredir),b)return!1}else if("_parent"==d.target.toLowerCase()){if(setTimeout('parent.location.href="'+d.href+'"',a.xttredir),b)return!1}else{if("_blank"==d.target.toLowerCase()&&(setTimeout('(xw.open("'+d.href+'","_blank")).focus();',
1),b))return!1}else if(setTimeout('AT_click.mail_to("'+d.href+'");',a.xttredir),b)return!1}else if(e||c.href)if(e=e?e:c.href,0>e.indexOf("mailto:"))if("_blank"==f)setTimeout('(xw.open("'+e+'","_blank")).focus();',1);else{if(setTimeout('self.location.href="'+e+'"',a.xttredir),b)return!1}else if(setTimeout('AT_click.mail_to("'+e+'");',a.xttredir),b)return!1;if(b)return O=!1,!0},do_submit:function(a,e,f){if(f&&(setTimeout(function(){a.submit()},500),e&&f))return!1},mail_to:function(a){window.location=
a}};window.AT_hit={first:!0,referrer:("acc_dir"==g("xtref")?"":null!==g("xtref")?g("xtref"):"acc_dir"==q("xtref")?"":q("xtref")||Aa.replace(/[<>]/g,"")||"").replace(/[<>]/g,"").substring(0,1600),parse:function(a,e,f,b){var d=[""];if(1600>=e.length)d[0]=e;else{a=AT_hit.first&&"F"==a?Ca:Ca.substring(0,6)+U(8);var h="",l="",m,n={};m=[];var j=0;0<=e.indexOf("&ref=")&&(h=e.substring(e.indexOf("&ref=")),e=e.replace(h,""));if(b)for(var q in b)if(b.hasOwnProperty(q)&&0<=e.indexOf("&"+q+"=")&&1600<(l=g(q,
e,2)).length)e=e.replace("&"+q+"="+l,""),m=RegExp("["+b[q]+"]","gi"),n[q]=l.replace(/&/g,"%26").split(m);m=RegExp("["+f+"]","gi");m=e.split(m);for(var s in m)m.hasOwnProperty(s)&&(1600>=d[j].length+m[s].length+1?d[j]+=""!==m[s]?"&"+m[s]:"":(d.push(""),j++,d[j]=1600>m[s].length?d[j]+(""!==m[s]?"&"+m[s]:""):d[j]+("&mherr=1&"+m[s].substring(0,1600))));for(var p in n)if(n.hasOwnProperty(p)){e="&"+p+"=";f=!1;q=n[p].length;for(s=0;s<q;s++)1600>=d[j].length+n[p][s].length+1?(f||(d[j]+=e,f=!0),d[j]+=""!==
n[p][s]?n[p][s]+("stc"===p&&q-1===s?"":b[p]):""):(d.push(e),f=!0,j++,d[j]=1600>n[p][s].length?d[j]+(""!==n[p][s]?n[p][s]+("stc"===p&&q-1===s?"":b[p]):""):d[j]+("mherr=1"+b[p]))}h&&(1600>=d[j].length+h.length||(d.push(""),j++),d[j]+=h);for(b=0;b<d.length;b++)d[b]="&mh="+(b+1)+"-"+d.length+"-"+a+d[b]}return d},sendTag:function(c,e,f,b){var d=[];f=f||Sb+Gb;f+=a.xtfirst?"&idclient="+F:"";c=c||"F";e=e||w;e+=(b?b:"")+"&vtag="+Cb+AT_hit.localHour()+AT_hit.resolution();AT_hit.first&&"F"==c&&(e+=eb?"&stc="+
eb:"",e+="&ref="+AT_hit.referrer.replace(/&/g,"$"));"C"===c&&(e+="&pclick="+J+"&s2click="+(h(a.xtn2)?a.xtn2:""));d=AT_hit.parse(c,e,"&",{ati:",",atc:",",pdtl:"|",stc:",",dz:"|"});for(e=0;e<d.length;e++)AT_hit.loadImage(f+d[e]);AT_hit.first&&("F"==c&&""!==Ya)&&AT_hit.loadFile("script",Ya,!0,"text/javascript");"F"==c&&(AT_hit.first=!1)},loadImage:function(a){var e=new Image;e.src=a;ra.sentHits instanceof Array&&ra.sentHits.push(a);e.onload=function(){e.onload=null}},loadFile:function(a,e,f,b,d){a=document.createElement(a);
a.type=b;a.async=f;a.src=e;(d||document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]||document.getElementsByTagName("script")[0].parentNode).insertBefore(a,null)},localHour:function(a){a=a?a:new Date;return"&hl="+a.getHours()+"x"+a.getMinutes()+"x"+a.getSeconds()},resolution:function(){if(4<=parseFloat(t.appVersion))try{return"&r="+fa.width+"x"+fa.height+"x"+fa.pixelDepth+"x"+fa.colorDepth}catch(a){}return""},prerenderDisplaying:function(){AT_hit.first&&(AT_hit.sendTag("F"),
""!==xt44&&AT_hit.sendTag("PDT",xt44,null,"&type=PDT&p="+J+(a.xt_pageID?"&pid="+a.xt_pageID+"&pchap="+(a.xt_chap||"")+"&pidt="+(a.xt_pageDate||""):"")))},isPreviewOrPrerendering:function(){return window.navigator&&"preview"===window.navigator.loadPurpose&&-1!=t.userAgent.indexOf("Safari")&&0>t.userAgent.indexOf("Chrome")?(wb&&(AT_hit.sendTag("F",null,null,"&pvw=1"),""!==xt44&&AT_hit.sendTag("PDT",xt44,null,"&type=PDT&p="+J+(a.xt_pageID?"&pid="+a.xt_pageID+"&pchap="+(a.xt_chap||"")+"&pidt="+(a.xt_pageDate||
""):""))),!0):"prerender"==j.webkitVisibilityState?(j.addEventListener("webkitvisibilitychange",AT_hit.prerenderDisplaying,!1),!0):!1}};if(0!==I||0!==ba||L){var W="";if(""!==bb){W=q("xtvid");W||(va=W=v.getTime()+""+U(6));var Da=new Date;Da.setMinutes(Da.getMinutes()+30);l("xtvid",W,Da,"",1)}window.xtvid=W;var lb=Xtconf.xtsite("xtor"),Ea=Xtconf.xtsite("xtdate"),mb=Xtconf.xtsite("xtocl"),Fa=Xtconf.xtsite("xtan"),Ga=Xtconf.xtsite("xtat"),X=Xtconf.xtsite("xtant"),N=g("xtor"),Ha=g("xtdt"),x=g("xtan"),
y=g("xtat"),Ia=g("an",p),Ja=g("at",p),nb=g("ac",p),ob=q(mb),Ka=q("xtgo"),La=q("xtord"),pb=q("xtvrn"),Y=null!==ob?ob:"$",Tb="0"===Ka?La:null,Ma=null!==Ka?Ka:"0",ga=null!==pb?pb:"$",qb=v.getTime()/6E4,Z=null!==Ha&&g("xts")==I?30>qb-Ha&&0<=qb-Ha?"2":"1":Ma,Ub="1"==Ma?"&pgt="+La:"1"==Z&&null!==N?"&pgt="+N:"",P=null!==fb?fb:null!==N&&"0"==Z?N:!L?Tb:null,P=0>Y.indexOf("$"+P+"$")||"$"==Y?P:null,C="0"==Z?P:"2"==Ma?La:"2"==Z?N:null,Q,Na;null!==C?(Na=C.substring(0,C.indexOf("-")),Q=A[Na]):Q="1";if(null===Q||
!h(Q))Q=A.ad;null===x&&!L&&(x=q("xtanrd"));null===y&&!L&&(y=q("xtatrd"));var rb=q(Fa),sb=q(Ga),ha=q(X),B=new Date,z=window.xt29=new Date,Oa=new Date;L?B.setTime(B.getTime()+3E4):B.setTime(B.getTime()+864E5*Q);Oa.setTime(Oa.getTime()+18E5);z.setTime(z.getTime()+864E5*Bb);var Pa=null!==x?x.indexOf("-"):0,Qa=null!==y?y.indexOf("-"):0,tb=null!==Ia?"":null!==x&&0<Pa?"&ac="+x.substring(0,Pa)+"&ant=0&an="+x.substring(Pa+1,x.length):null!==rb?"&anc="+rb+"&anct="+ha:"",Vb=null!==Ja?"":null!==y&&0<Qa?"&ac="+
y.substring(0,Qa)+"&ant=0&at="+y.substring(Qa+1,y.length):null!==sb?"&attc="+sb+"&anct="+ha:"",K=0>ga.indexOf("$"+I+"$")?"&vrn=1":"",Wb=null!==g("xtatc")&&null===g("atc",p)?"&atc="+g("xtatc"):"";""!==K&&l("xtvrn",141>ga.length?ga+I+"$":ga.substring(0,141),z,n,0);K+=null===P?"":"&xto="+P;K+=(""!==tb?tb:Vb)+Ub+Wb;null!==Ia?(l(Fa,nb+"-"+Ia,z,n,1),l(X,"1",z,n,1)):null!==x&&"1"!=ha&&(l(Fa,x,z,n,1),l(X,"0",z,n,1));null!==Ja?(l(Ga,nb+"-"+Ja,z,n,1),l(X,"1",z,n,1)):null!==y&&"1"!=ha&&(l(Ga,y,z,n,1),l(X,"0",
z,n,1));var Ra=q(lb),$=q(Ea),$=(/[a-zA-Z]/.test($)?(new Date($)).getTime()/36E5:parseFloat(q(Ea)))||(new Date).getTime()/36E5,Xb=0<=Math.floor(hb-$)?Math.floor(hb-$):0,K=K+(null===Ra?"":"&xtor="+Ra+"&roinbh="+Xb);if(L)l("xtgo",Z,B,n,1),null!==N&&l("xtord",N,B,n,1),null!==x&&l("xtanrd",x,B,n,1),null!==y&&l("xtatrd",y,B,n,1),l("xtref",AT_hit.referrer?AT_hit.referrer.replace(/&/g,"$"):"acc_dir",B,n,0),h(a.xtloc)&&(T.location=a.xtloc);else{null!==C&&(0>Y.indexOf("$"+encodeURIComponent(C)+"$")||"$"==Y)&&
l(mb,Y+C+"$",Oa,n,1);var ia=t.appName+" "+t.appVersion,R=ia.indexOf("MSIE"),S;0<=R?(S=parseInt(ia.substr(R+5)),R=!0):(S=parseFloat(t.appVersion),R=!1);var Yb=0<=ia.indexOf("Netscape"),Zb=0<=ia.indexOf("Mac"),Sa=0<=t.userAgent.indexOf("Opera"),ja="",ub="",Ta="",Ua="";if(R&&5<=S&&!Zb&&!Sa&&!L)try{j.body.addBehavior("#default#clientCaps"),ja="&cn="+j.body.connectionType,ja+="&ul="+j.body.UserLanguage,j.body.addBehavior("#default#homePage"),ub=j.body.isHomePage(location.href)?"&hm=1":"&hm=0",Ua="&re="+
j.body.offsetWidth+"x"+j.body.offsetHeight}catch(ec){}else 5<=S&&(Ua="&re="+a.innerWidth+"x"+a.innerHeight);Yb&&4<=S||Sa?Ta="&lng="+t.language:R&&(4<=S&&!Sa)&&(Ta="&lng="+t.userLanguage);l("xtord","",v,n,1);if(null!==C&&(null===Ra||"1"==Ab))l(lb,C,B,n,1),l(Ea,v.getTime()/36E5,B,n,1);var $b=zb?"&docl="+encodeURIComponent(T.location.href.replace(/&/g,"#ec#")):"",w=Fb+"&p="+J+Hb+Ib+Jb+K+$b+Kb+p+ja+ub+Ta+"&idp="+Ca,Va=q("xtvalCZ",1);if(null!==Va){var w=w+Va.replace("&c=","&current=").replace("&b=","&before=").replace("&a=",
"&after="),Wa=new Date;Wa.setTime(Wa.getTime()-36E5);l("xtvalCZ",Va,Wa,n,1)}var Sb=window.Xt_id=Db+"?",ka=q("xtide");if(null!==C)switch(Na.toLowerCase()){case "erec":case "epr":case "es":var la=null;try{var ma=C.match(/(\[[^\]]*\])|([^\-]+)|(-)/g),vb=0,na;for(na in ma)"-"==ma[na]&&vb++,5==vb&&"-"!=ma[na]&&(la=ma[na])}catch(fc){la=null}null!==la&&(ka=la,l("xtide",ka,z,"",1))}w+="&jv="+(t.javaEnabled()?"1":"0")+Ua+xt16+(null!==ka?"&ide="+ka:"");va&&(w+="&lnk="+bb+"&vid="+va);"0"!=aa&&!AT_hit.isPreviewOrPrerendering()&&
(AT_hit.sendTag("F"),""!==xt44&&AT_hit.sendTag("PDT",xt44,null,"&type=PDT&p="+J+(a.xt_pageID?"&pid="+a.xt_pageID+"&pchap="+(a.xt_chap||"")+"&pidt="+(a.xt_pageDate||""):"")))}}0<qa&&"function"==typeof xtNodesload&&(yb?a.addEventListener?a.addEventListener("load",xtNodesload,!1):a.attachEvent&&a.attachEvent("onload",xtNodesload):xtNodesload())};window.attag=new Xtcore;
