(function(g){var window=this;var cua=function(a,b){return g.Yb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.I)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.w,b,c)},dua=function(a,b){var c=[];
g.ik(b,function(d){try{var e=g.eo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.co(e)&&c.push(d)},a);
return c},eua=function(a,b){var c=dua(a,b);
(0,g.y)(c,function(d){g.eo.prototype.remove.call(this,d)},a)},fua=function(a,b){g.bb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},gua=function(a,b){var c=b instanceof g.Bc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Cc(c)},b6=function(){},hua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},iua=function(a){if(a.Bd&&"function"==typeof a.Bd)return a.Bd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ub(a)},jua=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.te&&"function"==typeof a.te)var c=a.te();else if(a.Bd&&"function"==typeof a.Bd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Vb(a);d=iua(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},kua=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Mo[a]=!0;
var c=g.Ko();c&&c.publish.apply(c,arguments);g.Mo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lua(this,a.capabilities||""),mua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},lua=function(a,b){a.capabilities.clear();
(0,g.ae)(b.split(","),g.Ra(cua,nua)).forEach(function(c){a.capabilities.add(c)})},mua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},oua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},pua=function(a){return new e6(a)},qua=function(a){return g.La(a)?(0,g.A)(a,pua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.La(a)?"["+(0,g.A)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rua=function(a){return(0,g.A)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.ms)(),c=(0,g.ls)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},sua=function(){var a=(0,g.ls)();
a&&eua(a,a.o.Jf(!0))},m6=function(){var a=g.os("yt-remote-connected-devices")||[];
g.sb(a);return a},tua=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.A)(a,function(d,e){return 0==e?d:d.substring(c.length)})},uua=function(a){g.ns("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.os("yt-remote-device-id");a||(a=i6(),g.ns("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.bb(a,b);g.ps()&&g.vb(a,b);a=tua(a);if(g.cb(a))try{g.dr("remote_sid")}catch(c){}else try{g.br("remote_sid",a.join(","),-1)}catch(c){}},vua=function(){return g.os("yt-remote-session-browser-channel")},wua=function(){return g.os("yt-remote-local-screens")||[]},xua=function(){g.ns("yt-remote-lounge-token-expiration",!0,86400)},yua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.A)(wua(),function(d){return d.loungeToken}),c=(0,g.A)(a,function(d){return d.loungeToken});
(0,g.si)(c,function(d){return!g.bb(b,d)})&&xua();
g.ns("yt-remote-local-screens",a,31536E3)},zua=function(a,b){g.ns("yt-remote-session-browser-channel",a);
g.ns("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.bb(c,d)||c.push(d);uua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.fb(a,o6());uua(a)},Aua=function(){if(!r6){var a=g.po();
a&&(r6=new g.Yn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Bua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Cua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Dua(a.shift(),function(){s6(a)}):t6()},Eua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Dua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Cua();
a&&a(!1,"No cast extension found")},Gua=function(){if(Fua){var a=2,b=Cua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Dua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Hua=function(){Gua();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(){},Iua=function(){},Kua=function(a){return(a=Jua(a))?new ActiveXObject(a):new XMLHttpRequest},Jua=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},v6=function(a,b,c){g.B.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.rd=b;this.u=(0,g.x)(this.bF,this);this.o=[]},w6=function(a){a.Da=g.Bf(a.u,a.rd);
a.w.apply(null,a.o)},x6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.T1(this);this.u=new g.Af;this.u.setInterval(250)},Mua=function(a,b,c){a.Xi=1;
a.Bg=Z5(b.clone());a.ni=c;a.C=!0;Lua(a,null)},y6=function(a,b,c,d,e){a.Xi=1;
a.Bg=Z5(b.clone());a.ni=null;a.C=c;e&&(a.HB=!1);Lua(a,d)},Lua=function(a,b){a.Hj=(0,g.I)();
z6(a);a.mh=a.Bg.clone();$5(a.mh,"t",a.F);a.km=0;a.Jc=a.o.Aq(a.o.Wl()?b:null);0<a.kr&&(a.Uo=new v6((0,g.x)(a.GC,a,a.Jc),a.kr));a.A.ia(a.Jc,"readystatechange",a.fO);var c=a.Sh?g.dc(a.Sh):{};a.ni?(a.Ep="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Jc.send(a.mh,a.Ep,a.ni,c)):(a.Ep="GET",a.HB&&!g.Qd&&(c.Connection="close"),a.Jc.send(a.mh,a.Ep,null,c));a.o.Te(1)},Pua=function(a,b,c){for(var d=!0;!a.Ch&&a.km<c.length;){var e=Nua(a,c);
if(e==A6){4==b&&(a.Ng=4,B6(15),d=!1);break}else if(e==Oua){a.Ng=4;B6(16);d=!1;break}else C6(a,e)}4==b&&0==c.length&&(a.Ng=1,B6(17),d=!1);a.Ue=a.Ue&&d;d||(D6(a),E6(a))},Nua=function(a,b){var c=a.km,d=b.indexOf("\n",c);
if(-1==d)return A6;c=Number(b.substring(c,d));if(isNaN(c))return Oua;d+=1;if(d+c>b.length)return A6;var e=b.substr(d,c);a.km=d+c;return e},Rua=function(a,b){a.Hj=(0,g.I)();
z6(a);var c=b?window.location.hostname:"";a.mh=a.Bg.clone();Y5(a.mh,"DOMAIN",c);Y5(a.mh,"t",a.F);try{a.Ye=new ActiveXObject("htmlfile")}catch(n){D6(a);a.Ng=7;B6(22);E6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in F6)k=F6[l];else if(l in Qua)k=F6[l]=Qua[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
F6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Xc(g.tc("b/12014412"),d+"</body></html>");a.Ye.open();a.Ye.write(g.Sc(c));a.Ye.close();a.Ye.parentWindow.m=(0,g.x)(a.xN,a);a.Ye.parentWindow.d=(0,g.x)(a.QA,a,!0);a.Ye.parentWindow.rpcClose=(0,g.x)(a.QA,a,!1);c=a.Ye.createElement("DIV");a.Ye.parentWindow.document.body.appendChild(c);d=g.Ec(a.mh.toString());d=g.dd(g.Cc(d));d=g.Xc(g.tc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Yc(c,d);a.o.Te(1)},z6=function(a){a.Hu=(0,g.I)()+a.B;
Sua(a,a.B)},Sua=function(a,b){if(null!=a.Uj)throw Error("WatchDog timer not null");
a.Uj=G6((0,g.x)(a.FN,a),b)},H6=function(a){a.Uj&&(g.v.clearTimeout(a.Uj),a.Uj=null)},E6=function(a){a.o.yx()||a.Ch||a.o.Mo(a)},D6=function(a){H6(a);
g.me(a.Uo);a.Uo=null;a.u.stop();g.bpa(a.A);if(a.Jc){var b=a.Jc;a.Jc=null;b.abort();b.dispose()}a.Ye&&(a.Ye=null)},C6=function(a,b){try{a.o.KA(a,b),a.o.Te(4)}catch(c){}},Uua=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Tua(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Uua(a,b,c,d,f)},f)})}},Tua=function(a,b,c){var d=new Image;
d.onload=function(){try{I6(d),c(!0)}catch(e){}};
d.onerror=function(){try{I6(d),c(!1)}catch(e){}};
d.onabort=function(){try{I6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{I6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
gua(d,a)},I6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},J6=function(){},Vua=function(a){this.o=a;
this.u=new J6},Wua=function(a){var b=K6(a.o,a.fk,"/mail/images/cleardot.gif");
Z5(b);Uua(b.toString(),5E3,(0,g.x)(a.YD,a),3,2E3);a.Te(1)},M6=function(a){var b=a.o.H;
if(null!=b)B6(5),b?(B6(11),L6(a.o,a,!1)):(B6(12),L6(a.o,a,!0));else if(a.Rd=new x6(a,void 0,void 0,void 0),a.Rd.Sh=a.ir,b=a.o,b=K6(b,b.Wl()?a.Gk:null,a.jr),B6(5),!g.Od||g.rd(10))$5(b,"TYPE","xmlhttp"),y6(a.Rd,b,!1,a.Gk,!1);else{$5(b,"TYPE","html");var c=a.Rd;a=!!a.Gk;c.Xi=3;c.Bg=Z5(b.clone());Rua(c,a)}},N6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return hua(a)},O6=function(a){g.Me.call(this);
this.headers=new g.Nm;this.S=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.J=null;this.ea="";this.P=this.V=!1},Xua=function(a){return g.Od&&g.qd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Yua=function(a){return"content-type"==a.toLowerCase()},$ua=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;Zua(a);P6(a)},Zua=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},bva=function(a){if(a.w&&"undefined"!=typeof g.Y1)if(a.O[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.G&&4==Q6(a))g.Bf(a.Ax,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Vg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!ava.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";Zua(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){cva(a);
var c=a.o,d=a.O[0]?g.Ia:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},cva=function(a){a.o&&a.P&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new J6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},dva=function(a,b){this.o=a;
this.map=b;this.context=null},eva=function(a){g.oe.call(this,"statevent",a)},fva=function(a,b){g.oe.call(this,"timingevent",a);
this.size=b},gva=function(a){g.oe.call(this,"serverreachability",a)},jva=function(a){hva(a);
if(3==a.o){var b=a.Al++,c=a.mn.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new x6(a,a.w,b,void 0);b.Xi=2;b.Bg=Z5(c.clone());gua(new Image,b.Bg.toString());b.Hj=(0,g.I)();z6(b)}iva(a)},kva=function(a){a.uE(1,0);
a.mn=K6(a,null,a.gr);V6(a)},hva=function(a){a.Fg&&(a.Fg.abort(),a.Fg=null);
a.fc&&(a.fc.cancel(),a.fc=null);a.Lf&&(g.v.clearTimeout(a.Lf),a.Lf=null);W6(a);a.Kd&&(a.Kd.cancel(),a.Kd=null);a.Jg&&(g.v.clearTimeout(a.Jg),a.Jg=null)},lva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new dva(a.OJ++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.Kd||a.Jg||(a.Jg=G6((0,g.x)(a.PA,a),0),a.Ri=0)},nva=function(a,b){if(1==a.o){if(!b){a.Al=Math.floor(1E5*Math.random());
var c=a.Al++,d=new x6(a,"",c,void 0);d.Sh=null;var e=X6(a),f=a.mn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);Mua(d,f,e);a.Kd=d;a.o=2}}else 3==a.o&&(b?mva(a,b):0==a.u.length||a.Kd||mva(a))},mva=function(a,b){if(b)if(6<a.Dh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Al-1;var d=X6(a)}else c=b.G,d=b.ni;else c=a.Al++,d=X6(a);var e=a.mn.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.kj);U6(a,e);c=new x6(a,a.w,c,a.Ri+1);c.Sh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Kd=c;Mua(c,e,d)},U6=function(a,b){if(a.od){var c=a.od.Uw();
c&&g.Ob(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Dh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Dh?e:f-d;try{g.Ob(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},ova=function(a){a.fc||a.Lf||(a.F=1,a.Lf=G6((0,g.x)(a.OA,a),0),a.Ki=0)},Y6=function(a){if(a.fc||a.Lf||3<=a.Ki)return!1;
a.F++;a.Lf=G6((0,g.x)(a.OA,a),pva(a,a.Ki));a.Ki++;return!0},L6=function(a,b,c){a.Cp=c;
a.kf=b.Xf;a.C||kva(a)},W6=function(a){null!=a.Hh&&(g.v.clearTimeout(a.Hh),a.Hh=null)},pva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.x)(a.QO,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),Z5(c));Tua(c.toString(),1E4,d)}else B6(2);qva(a,b)},qva=function(a,b){a.o=0;
a.od&&a.od.iw(b);iva(a);hva(a)},iva=function(a){a.o=0;
a.kf=-1;if(a.od)if(0==a.A.length&&0==a.u.length)a.od.qq();else{g.jb(a.A);var b=g.jb(a.u);a.A.length=0;a.u.length=0;a.od.qq(b)}},K6=function(a,b,c){var d=g.Ym(c);
if(""!=d.o)b&&g.Sm(d,b+"."+d.o),g.Tm(d,d.B);else{var e=window.location;d=kua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.uk&&g.Ob(a.uk,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.Dh);U6(a,d);return d},G6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){$6.dispatchEvent(new eva($6,a))},rva=function(){},a7=function(a,b,c){g.B.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.rd=b;this.B=(0,g.x)(this.aF,this);this.o=!1;this.u=0;this.w=this.Da=null;this.A=[]},sva=function(){this.o=[];
this.u=[]},tva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.o=new g.J(this.oN,0,this);g.H(this,this.o);this.rd=5E3;this.u=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Xn;this.u=new b7(this.uO,this);this.o=null;this.vb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.P=c||!1},uva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Cp,sessionId:a.o.w,arrayId:a.o.kj}},vva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&nva(a.o),jva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},wva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Vg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Mb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Lb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.eh(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.A,d,!0),onError:g.Ra(a.w,e),Nd:g.Ra(a.B,e)};c&&(a.zb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wp(b,a)},Ava=function(){var a=xva;
yva();h7.push(a);zva(h7)},i7=function(a,b){yva();
var c=h7,d=Bva(a,String(b));g.cb(c)?Cva(d):(zva(c),(0,g.y)(c,function(e){e(d)}))},yva=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",h7,void 0))},Cva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},zva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Bva=function(a,b){var c=((0,g.I)()-Dva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},Eva=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Fva=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ae)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Eva(a,b[d])||c;return c},Gva=function(a,b){var c=a.o.length;
a.o=(0,g.ae)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Da=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Hva=function(a){if(a.o.length){var b=(0,g.A)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.lF,a),(0,g.x)(a.kF,a))}},o7=function(a){var b=qua(wua());
b=(0,g.ae)(b,function(c){return!c.uuid});
return Fva(a,b)},q7=function(a,b){yua((0,g.A)(a.o,oua));
b&&xua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.os("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Kk(this.o))},Iva=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Vb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Kk(a.o)),a.o=b,a.R("screenChange"));Jva(a)},u7=function(a){isNaN(a.w)||g.Jo(a.w);
a.w=g.Ho((0,g.x)(a.Qt,a),0<a.A&&a.A<(0,g.I)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Kva=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Sb("Requesting availability of screen w/o lounge token.")});
return b},Jva=function(a){a=g.Vb(g.Pb(a.o,function(b){return b}));
g.sb(a);a.length?g.ns("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Lva(this)},Nva=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ce();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);Iva(a.u,l,function(m){e(m?l:null)})}else c?Mva(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Iva(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},Ova=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Mva=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={zb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Pva=function(a){a.o=a.w.ce();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},Lva=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.tF,a));Pva(a);a.A=qua(g.os("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.ce,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ns("yt-remote-automatic-screen-cache",(0,g.A)(a.A,oua)));x7(a);a.B[b.uuid]=b.id;g.ns("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.os("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.DP,this);this.B=(0,g.x)(this.NN,this);this.A=g.Ho((0,g.x)(function(){Qva(this,null)},this),12E4)},Rva=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Kk(b))},Qva=function(a,b){g.Jo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.Oo,a),d=(0,g.x)(a.ie,a);a.ox(b,c,d,5)}}else a.ie(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.S=c;this.B=null;this.F=g.Ia;this.C=NaN;this.P=(0,g.x)(this.GP,this);this.o=g.Ia},Sva=function(a){a.o=a.H.MC(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ia;
this.Oo(b)},a),(0,g.x)(function(b){this.o=g.Ia;
this.ie(b)},a))},Tva=function(a){var b={};
b.pairingCode=a.J;b.theme=a.S;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Aua()&&(b.env_useStageMdx=1);return g.ch(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Ho((0,g.x)(this.lj,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.vM,this)},Uva=function(a,b){return b?g.Za(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},xva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.me(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.NA,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.lj(null)):a.R("yt-remote-cast2-session-change",null))},Vva=function(a){var b=a.u.LC(),c=a.o&&a.o.u;
a=(0,g.A)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Uva(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},awa=function(a,b,c,d,e,f,k){Wva()?Xva(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Yva(a,c):(window.__onGCastApiAvailable=function(l,m){l?Yva(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Zva(),c(!1))},d?g.To("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Hua():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Gua(),s6($va.map(Eua))))):H7("Cannot initialize because not running Chrome")},Zva=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);bwa(!1);g.Po(M7);M7.length=0},N7=function(){return!!g.os("yt-remote-cast-installed")},cwa=function(){var a=g.os("yt-remote-cast-receiver");
return a?a.friendlyName:null},dwa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},ewa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Oo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Wva=function(){var a=0<=g.Mb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Gv||a},fwa=function(a,b){L7().init(a,b)},Xva=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ns("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.ns("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.ns("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Yva=function(a,b){K7(!0);
I7(!1);fwa(a,function(c){c?(bwa(!0),g.Qo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Zva());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.ns("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},bwa=function(a){H7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.lf=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.lf=!1;a.hasNext=!1;a.F=0;a.C=(0,g.I)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.I)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.I)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.o);b.hasPrevious=a.lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new sva;this.w=this.u=null;this.H=(0,g.x)(this.wK,this);this.F=(0,g.x)(this.Cl,this);this.G=(0,g.x)(this.vK,this);this.J=(0,g.x)(this.HK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ku,this),gwa(this))):c=3;0!=c&&(b?this.Ku(c):g.Ho((0,g.x)(function(){this.Ku(c)},this),0));
var d=ewa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},gwa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Ra(this.sM,b),this))},a)},hwa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){hwa(a);
a.A.setPlayerContextData(X7(b));gwa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.Cl(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.Cl(a.w.media[0]))},iwa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Sb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.P=!1;this.G=this.F=this.H=this.J=NaN;this.O=[];this.A=this.C=this.w=this.Sa=this.o=null;this.U=a;this.O.push(g.Fq(window,"beforeunload",(0,g.x)(this.dF,this)));this.u=[];this.Sa=new R7;this.S=b.id;this.o=jwa(this,c);this.o.subscribe("handlerOpened",this.AK,this);this.o.subscribe("handlerClosed",this.xK,this);this.o.subscribe("handlerError",this.yK,this);this.o.subscribe("handlerMessage",this.zK,this);wva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.ps()&&g.ns("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},jwa=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},kwa=function(a){a.B=g.Ho((0,g.x)(function(){g8("Connecting timeout");
this.Pi(1)},a),2E4)},i8=function(a){g.Jo(a.B);
a.B=NaN},j8=function(a){g.Jo(a.J);
a.J=NaN},lwa=function(a){k8(a);
a.H=g.Ho((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Jo(a.H);
a.H=NaN},nwa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.mx()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),mwa(a)):a.Pi(1)},owa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.ac(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},pwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},rwa=function(a,b){b.params=b.params||{};
pwa(a,b);qwa(a,b);a.R("autoplayDismissed")},qwa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?lwa(a):k8(a);a.R("remotePlayerChange")},swa=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},twa=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},uwa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},vwa=function(a,b){var c="true"==b.params.hasNext;
a.Sa.lf="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},mwa=function(a){g.Jo(a.G);
a.G=g.Ho((0,g.x)(a.Pi,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Kk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.qd=a;this.u=[];this.u.push(this.qd.$_s("screenChange",(0,g.x)(this.BP,this)));this.u.push(this.qd.$_s("onlineScreenChange",(0,g.x)(this.XL,this)))},Awa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;sua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Aua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",o8,void 0));wwa();var c=p8();if(!c){var d=new v7(n8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);awa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Kk(b)),s8.push(g.Oo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.Oo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Oo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Oo("yt-remote-cast2-session-change",xwa)),s8.push(g.Oo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),dwa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Xo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Kk(a)),ywa(a),c.start(),q8()||zwa())},Cwa=function(){var a=Bwa();
N7()&&g.os("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Bwa=function(){var a=p8().qd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return rua(a)},y8=function(){var a=Dwa();
!a&&N7()&&cwa()&&(a={key:"cast-selector-receiver",name:cwa()});return a},Dwa=function(){var a=Bwa(),b=w8();
b||(b=u8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().ce();return k6(b,a)},xwa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Ewa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},Fwa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Ewa("");g.Ha("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.ps();
if(!a)return null;var b=p8().ce();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Ewa(a.id);var c=new f8(n8,a,v8());c.connect(b,Fwa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},zwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),dwa(),r8("Skipping connecting because no session screen found."))},wwa=function(){var a=v8();
if(g.ac(a)){a=o6();var b=g.os("yt-remote-session-name")||"",c=g.os("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ywa=function(a){a?(g.ns("yt-remote-session-app",a.app),g.ns("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.B.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.H(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.tL);this.w.L(b,"captionschanged",this.uK);this.w.L(b,"captionssettingschanged",this.aC);this.w.L(b,"videoplayerreset",this.Po);this.w.L(b,"mdxautoplaycancel",this.XD);this.S=this.w.L(b,"onVolumeChange",this.uA);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.JA,this);c.subscribe("remotePlayerChange",this.Gl,this);c.subscribe("remoteQueueChange",this.Po,this);c.subscribe("autoplayUpNext",this.kA,
this);c.subscribe("previousNextChange",this.GA,this);c.subscribe("nowAutoplaying",this.CA,this);c.subscribe("autoplayDismissed",this.jA,this);this.suggestion=null;this.H=new g.pD(64);this.A=new g.J(this.YB,500,this);g.H(this,this.A);this.C=new g.J(this.ZB,1E3,this);g.H(this,this.C);this.P=new a7(this.bP,0,this);g.H(this,this.P);this.F={};this.O=new g.J(this.zC,1E3,this);g.H(this,this.O);this.J=new v6(this.WH,1E3,this);g.H(this,this.J);this.U=g.Ia;this.aC();this.Po();this.Gl()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},Gwa=function(a){H8(a,0);
a.A.stop();I8(a,new g.pD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.gc(c,b));a.o.NB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Xa;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.nf,g.yB(c));I8(a,new g.pD(1))},Hwa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{wT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.vD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.nT(a.u.app,d);a.H=b;Iwa(a.B,c,b)}},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.dM(this,250);g.H(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.fM()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.dM(this,250);g.H(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);Jwa(this,g.sL(a))},Jwa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.JM("Error on $RECEIVER_NAME",c):g.wD(b)||g.W(b,4)?g.JM("Playing on $RECEIVER_NAME",c):g.JM("Connected to $RECEIVER_NAME",c);a.ha("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.BO.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.LP.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.S=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.pD(64);this.O=0;this.H=-1;this.C=null;if(!g.Jx(this.player.N())){a=this.player;var b=g.WC(a);b&&(b=b.tl())&&(b=new O8(a,b),g.H(this,b));b=new N8(a);g.H(this,b);g.KL(a,b.element,4);this.C=new M8;g.H(this,this.C);g.KL(a,this.C.element,4);this.P=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Iwa=function(a,b,c){a.F=
c;
a.player.R("presentingplayerstatechange",new g.BD(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.P||!a.C);if(c?0:g.Sx(a.player.N())||"WEB_EMBEDDED_PLAYER"==a.player.N().deviceParams.c)g.wD(g.sL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.SN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.U||1==a.player.app.U)&&g.R(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.nf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=g.yB(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Kk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().ce(),(c=k6(c,b.key))&&A8(c,1))}},Qua={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},F6={"'":"\\'"},Kwa={},nua={eQ:"atp",JS:"ska",yS:"que",RR:"mus",IS:"sus",dR:"dsp",FS:"seq"};
d6.prototype.Gg=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",Fua=Bua("loadCastFramework")||Bua("loadCastApplicationFramework"),$va=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];u6.prototype.o=null;u6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Jua(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ta(Iua,u6);S8=new Iua;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(v6,g.B);g.h=v6.prototype;g.h.Wi=!1;g.h.Fk=0;g.h.Da=null;g.h.xx=function(a){this.o=arguments;this.Da||this.Fk?this.Wi=!0:w6(this)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null,this.Wi=!1,this.o=[])};
g.h.pause=function(){this.Fk++};
g.h.resume=function(){this.Fk--;this.Fk||!this.Wi||this.Da||(this.Wi=!1,w6(this))};
g.h.Y=function(){v6.Gb.Y.call(this);this.stop()};
g.h.bF=function(){this.Da=null;this.Wi&&!this.Fk&&(this.Wi=!1,w6(this))};g.h=x6.prototype;g.h.Sh=null;g.h.Ue=!1;g.h.Uj=null;g.h.Hu=null;g.h.Hj=null;g.h.Xi=null;g.h.Bg=null;g.h.mh=null;g.h.ni=null;g.h.Jc=null;g.h.km=0;g.h.Ye=null;g.h.Ep=null;g.h.Ng=null;g.h.Hk=-1;g.h.HB=!0;g.h.Ch=!1;g.h.kr=0;g.h.Uo=null;var Oua={},A6={};g.h=x6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.fO=function(a){a=a.target;var b=this.Uo;b&&3==Q6(a)?b.xx():this.GC(a)};
g.h.GC=function(a){try{if(a==this.Jc)a:{var b=Q6(this.Jc),c=this.Jc.C,d=this.Jc.getStatus();if(g.Od&&!g.rd(10)||g.Qd&&!g.qd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.wh&&!S6(this.Jc))break a;this.Ch||4!=b||7==c||(8==c||0>=d?this.o.Te(3):this.o.Te(2));H6(this);var e=this.Jc.getStatus();this.Hk=e;var f=S6(this.Jc);(this.Ue=200==e)?(4==b&&D6(this),this.C?(Pua(this,b,f),g.wh&&this.Ue&&3==b&&(this.A.ia(this.u,"tick",this.ZN),this.u.start())):C6(this,f),this.Ue&&!this.Ch&&(4==b?this.o.Mo(this):(this.Ue=
!1,z6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ng=3,B6(13)):(this.Ng=0,B6(14)),D6(this),E6(this))}}catch(k){this.Jc&&S6(this.Jc)}finally{}};
g.h.ZN=function(){var a=Q6(this.Jc),b=S6(this.Jc);this.km<b.length&&(H6(this),Pua(this,a,b),this.Ue&&4!=a&&z6(this))};
g.h.xN=function(a){G6((0,g.x)(this.wN,this,a),0)};
g.h.wN=function(a){this.Ch||(H6(this),C6(this,a),z6(this))};
g.h.QA=function(a){G6((0,g.x)(this.vN,this,a),0)};
g.h.vN=function(a){this.Ch||(D6(this),this.Ue=a,this.o.Mo(this),this.o.Te(4))};
g.h.cancel=function(){this.Ch=!0;D6(this)};
g.h.FN=function(){this.Uj=null;var a=(0,g.I)();0<=a-this.Hu?(2!=this.Xi&&this.o.Te(3),D6(this),this.Ng=2,B6(18),E6(this)):Sua(this,this.Hu-a)};
g.h.getLastError=function(){return this.Ng};J6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=Vua.prototype;g.h.ir=null;g.h.Rd=null;g.h.Vo=!1;g.h.zx=null;g.h.jn=null;g.h.Qr=null;g.h.jr=null;g.h.ye=null;g.h.Xf=-1;g.h.Gk=null;g.h.fk=null;g.h.connect=function(a){this.jr=a;a=K6(this.o,null,this.jr);B6(3);this.zx=(0,g.I)();var b=this.o.G;null!=b?(this.Gk=b[0],(this.fk=b[1])?(this.ye=1,Wua(this)):(this.ye=2,M6(this))):($5(a,"MODE","init"),this.Rd=new x6(this,void 0,void 0,void 0),this.Rd.Sh=this.ir,y6(this.Rd,a,!1,null,!0),this.ye=0)};
g.h.YD=function(a){if(a)this.ye=2,M6(this);else{B6(4);var b=this.o;b.kf=b.Fg.Xf;Z6(b,9)}a&&this.Te(2)};
g.h.Aq=function(a){return this.o.Aq(a)};
g.h.abort=function(){this.Rd&&(this.Rd.cancel(),this.Rd=null);this.Xf=-1};
g.h.yx=function(){return!1};
g.h.KA=function(a,b){this.Xf=a.Hk;if(0==this.ye)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.kf=this.Xf;Z6(c,2);return}this.Gk=c[0];this.fk=c[1]}else c=this.o,c.kf=this.Xf,Z6(c,2);else if(2==this.ye)if(this.Vo)B6(7),this.Qr=(0,g.I)();else if("11111"==b){if(B6(6),this.Vo=!0,this.jn=(0,g.I)(),c=this.jn-this.zx,!g.Od||g.rd(10)||500>c)this.Xf=200,this.Rd.cancel(),B6(12),L6(this.o,this,!0)}else B6(8),this.jn=this.Qr=(0,g.I)(),this.Vo=!1};
g.h.Mo=function(){this.Xf=this.Rd.Hk;if(this.Rd.Ue)0==this.ye?this.fk?(this.ye=1,Wua(this)):(this.ye=2,M6(this)):2==this.ye&&((!g.Od||g.rd(10)?!this.Vo:200>this.Qr-this.jn)?(B6(11),L6(this.o,this,!1)):(B6(12),L6(this.o,this,!0)));else{0==this.ye?B6(9):2==this.ye&&B6(10);var a=this.o;this.Rd.getLastError();a.kf=this.Xf;Z6(a,2)}};
g.h.Wl=function(){return this.o.Wl()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Te=function(a){this.o.Te(a)};g.Ta(O6,g.Me);var ava=/^https?$/i,Lwa=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.S?Kua(this.S):Kua(S8);this.O=this.S?this.S.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Ax,this);try{b6(R6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));$ua(this,f);return}a=c||
"";var e=this.headers.clone();d&&jua(d,function(f,k){e.set(k,f)});
d=g.Za(e.te(),Yua);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(Lwa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{cva(this),0<this.F&&(this.P=Xua(this.o),b6(R6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.P)),this.P?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Bx,this)):this.J=g.Bf(this.Bx,this.F,this)),b6(R6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(R6(this,"Send error: "+f.message)),$ua(this,f)}};
g.h.Bx=function(){"undefined"!=typeof g.Y1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,R6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(R6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),P6(this,!0));O6.Gb.Y.call(this)};
g.h.Ax=function(){this.la()||(this.Z||this.G||this.B?bva(this):this.uM())};
g.h.uM=function(){bva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=T6.prototype;g.h.uk=null;g.h.Kd=null;g.h.fc=null;g.h.gr=null;g.h.mn=null;g.h.Uv=null;g.h.Dn=null;g.h.Al=0;g.h.OJ=0;g.h.od=null;g.h.Jg=null;g.h.Lf=null;g.h.Hh=null;g.h.Fg=null;g.h.Cp=null;g.h.kj=-1;g.h.ly=-1;g.h.kf=-1;g.h.Ri=0;g.h.Ki=0;g.h.Dh=8;var $6=new g.Me;g.Ta(eva,g.oe);g.Ta(fva,g.oe);g.Ta(gva,g.oe);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){B6(0);this.gr=b;this.uk=c||{};d&&void 0!==e&&(this.uk.OSID=d,this.uk.OAID=e);this.C?(G6((0,g.x)(this.ow,this,a),100),kva(this)):this.ow(a)};
g.h.ow=function(a){this.Fg=new Vua(this);this.Fg.ir=null;this.Fg.u=this.B;this.Fg.connect(a)};
g.h.yx=function(){return 0==this.o};
g.h.PA=function(a){this.Jg=null;nva(this,a)};
g.h.OA=function(){this.Lf=null;this.fc=new x6(this,this.w,"rpc",this.F);this.fc.Sh=null;this.fc.kr=0;var a=this.Uv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.Cp?"0":"1");Y5(a,"AID",this.kj);U6(this,a);if(!g.Od||g.rd(10))Y5(a,"TYPE","xmlhttp"),y6(this.fc,a,!0,this.Dn,!1);else{Y5(a,"TYPE","html");var b=this.fc,c=!!this.Dn;b.Xi=3;b.Bg=Z5(a.clone());Rua(b,c)}};
g.h.KA=function(a,b){if(0!=this.o&&(this.fc==a||this.Kd==a))if(this.kf=a.Hk,this.Kd==a&&3==this.o)if(7<this.Dh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Lf){if(this.fc)if(this.fc.Hj+3E3<this.Kd.Hj)W6(this),this.fc.cancel(),this.fc=null;else break a;Y6(this);B6(19)}}else this.ly=c[1],0<this.ly-this.kj&&37500>c[2]&&this.Cp&&0==this.Ki&&!this.Hh&&(this.Hh=G6((0,g.x)(this.qK,this),6E3));else Z6(this,11)}else b!=Kwa.BQ.o&&Z6(this,11);else if(this.fc==
a&&W6(this),!g.zb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.kj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.Dn=e[2],e=e[3],null!=e?this.Dh=e:this.Dh=6,this.o=3,this.od&&this.od.kw(),this.Uv=K6(this,this.Wl()?this.Dn:null,this.gr),ova(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.od&&this.od.jw(e),this.Ki=0)}}};
g.h.qK=function(){null!=this.Hh&&(this.Hh=null,this.fc.cancel(),this.fc=null,Y6(this),B6(20))};
g.h.Mo=function(a){if(this.fc==a){W6(this);this.fc=null;var b=2}else if(this.Kd==a)this.Kd=null,b=1;else return;this.kf=a.Hk;if(0!=this.o)if(a.Ue)1==b?(b=(0,g.I)()-a.Hj,$6.dispatchEvent(new fva($6,a.ni?a.ni.length:0,b,this.Ri)),V6(this),this.A.length=0):ova(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.kf)){if(d=1==b)this.Kd||this.Jg||1==this.o||2<=this.Ri?d=!1:(this.Jg=G6((0,g.x)(this.PA,this,a),pva(this,this.Ri)),this.Ri++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.uE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.QO=function(a){a?B6(2):(B6(1),qva(this,8))};
g.h.Aq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.V=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.Te=function(a){$6.dispatchEvent(new gva($6,a))};
g.h.Wl=function(){return!(!g.Od||g.rd(10))};
g.h=rva.prototype;g.h.kw=function(){};
g.h.jw=function(){};
g.h.iw=function(){};
g.h.qq=function(){};
g.h.Uw=function(){return{}};
g.h.isActive=function(){return!0};g.Ta(a7,g.B);g.h=a7.prototype;g.h.ZE=function(a){this.A=arguments;this.o=!1;this.Da?this.w=(0,g.I)()+this.rd:this.Da=g.Bf(this.B,this.rd)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();a7.Gb.Y.call(this)};
g.h.aF=function(){this.w?(this.Da=g.Bf(this.B,this.w-(0,g.I)()),this.w=null):(this.Da=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.h=sva.prototype;g.h.isEmpty=function(){return g.cb(this.o)&&g.cb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.gpa)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.u,a)};
g.h.Bd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(b7,g.B);g.h=b7.prototype;g.h.oN=function(){this.rd=Math.min(3E5,2*this.rd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.rd+15E3*Math.random();g.zn(this.o,a);this.u=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.rd=5E3};g.Ta(c7,rva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.og=function(a){return this.w.Th(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.vb||(this.vb=!0,g.me(this.w),vva(this),g.me(this.u),this.u=null)};
g.h.la=function(){return this.vb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.o;e&&(e.od=null);d.od=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.kj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&lva(this.o,c)};
g.h.kw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)lva(this.o,a[b])}this.R("handlerOpened")};
g.h.iw=function(a){var b=2==a&&401==this.o.kf;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.qq=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Uw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.gc(a,this.B);return a};
g.h.jw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),jva(this.o)):this.R("handlerMessage",new tva(a[0],a[1]))};
g.h.uO=function(){this.u.isActive();var a=this.o,b=0;a.fc&&b++;a.Kd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Dva=(0,g.I)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ta(m7,g.Q);m7.prototype.ce=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Da)&&this.KC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Da)||(g.Jo(this.Da),this.Da=NaN)};
g.h.Y=function(){this.stop();g.Q.prototype.Y.call(this)};
g.h.KC=function(){this.Da=NaN;this.o=g.wp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.zP,this),onError:(0,g.x)(this.yP,this),Nd:(0,g.x)(this.AP,this)})};
g.h.zP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.R("pairingComplete",new e6(c))};
g.h.yP=function(a){this.o=null;a.status&&404==a.status?this.u>=Mwa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=Mwa[this.u],this.Da=g.Ho((0,g.x)(this.KC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.AP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var Mwa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.os("yt-remote-lounge-token-expiration")&&Hva(this);g.Jo(this.u);this.u=g.Ho((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Eva(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Hva(this)};
g.h.remove=function(a,b){var c=o7(this);Gva(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.zp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Y=function(){g.Jo(this.u);p7.Gb.Y.call(this)};
g.h.lF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.kF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.os("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.I)()-144E5<a?0:a)?u7(this):(this.A=(0,g.I)()+3E5,g.ns("yt-remote-fast-check-period",this.A),this.Qt())};
g.h.isEmpty=function(){return g.ac(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Pb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.Jo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.Y.call(this)};
g.h.Qt=function(){g.Jo(this.w);this.w=NaN;this.u&&this.u.abort();var a=Kva(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Vb(a).join(",")},(0,g.x)(this.SM,this,a),(0,g.x)(this.RM,this))}else t7(this,{}),u7(this)};
g.h.SM=function(a,b){this.u=null;var c=g.Vb(Kva(this));if(g.ub(c,g.Vb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Sb("Changing Screen set during request."),this.Qt()};
g.h.RM=function(a){this.Sb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Sb=function(a){i7("OnlineScreenService",a)};g.Ta(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.zp=function(a,b,c,d){this.w.contains(a)?this.w.zp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.ce=function(a){return a?this.o:g.ib(this.o,(0,g.ae)(this.A,function(b){return!this.contains(b)},this))};
g.h.LC=function(){return(0,g.ae)(this.ce(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.MC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.me(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.me(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.CP=function(a,b,c,d){g.wp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Ova(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Ova(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.me(this.w);g.me(this.u);v7.Gb.Y.call(this)};
g.h.tF=function(){Pva(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ta(y7,g.Q);g.h=y7.prototype;g.h.Oo=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.ie=function(a){this.la()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.OC=function(){return null};
g.h.Zt=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Zt("");y7.Gb.Y.call(this)};g.Ta(A7,y7);g.h=A7.prototype;g.h.Yt=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Rva(this)};
g.h.lj=function(a){this.info("launchWithParams no-op for Cast: "+g.Kk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.ie()},this),(0,g.x)(function(){this.ie(Error("Failed to stop receiver app."))},this)):this.ie(Error("Stopping cast device witout session."))};
g.h.Zt=g.Ia;g.h.Y=function(){this.info("disposeInternal");g.Jo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Gb.Y.call(this)};
g.h.NN=function(a,b){if(!this.la())if(b){var c=N6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kk(c));switch(d){case "mdxSessionStatus":Qva(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.ox=function(a,b,c,d){Nva(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ho((0,g.x)(this.ox,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.OC=function(){return this.o};
g.h.DP=function(a){this.la()||a||(z7(this,"Cast session died."),this.ie())};g.Ta(B7,y7);g.h=B7.prototype;g.h.Yt=function(a){this.A=a;this.A.addUpdateListener(this.P)};
g.h.lj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A?this.A.stop((0,g.x)(this.ie,this,null),(0,g.x)(this.ie,this,"Failed to stop DIAL device.")):this.ie()};
g.h.Y=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A&&this.A.removeUpdateListener(this.P);this.A=null;B7.Gb.Y.call(this)};
g.h.GP=function(a){this.la()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.ie())};
g.h.xr=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Tva(this));a(b);Sva(this)}else this.F=(0,g.x)(function(){g.Jo(this.C);this.F=g.Ia;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Tva(this));a(c);Sva(this)},this),this.C=g.Ho((0,g.x)(function(){this.F()},this),100)};
g.h.NF=function(a,b,c){Nva(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Oo(d),b(new chrome.cast.DialLaunchResponse(!1))):this.xr(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.xr(b,c)},this))};g.Ta(C7,y7);C7.prototype.stop=function(){this.ie()};
C7.prototype.Yt=g.Ia;C7.prototype.lj=function(){g.Jo(this.o);this.o=NaN;var a=k6(this.H.ce(),this.u.label);a?this.Oo(a):this.ie(Error("No such screen"))};
C7.prototype.Y=function(){g.Jo(this.o);this.o=NaN;C7.Gb.Y.call(this)};g.Ta(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.MA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.PK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.A),Ava(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.NC,this)),this.w=Vva(this),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.x)(function(k){this.Sb("Failed to set initial custom receivers: "+g.Kk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Sb("Failed to initialize API: "+g.Kk(k));
b(!1)},this))};
g.h.CO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.ce(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Uva(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ia,(0,g.x)(function(e){this.Sb("Failed to set initial custom receivers: "+g.Kk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Zt(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.DO=function(a){this.la()?this.Sb("Setting connection data on disposed cast v2"):this.o?this.o.lj(a):this.Sb("Setting connection data without a session")};
g.h.FP=function(){this.la()?this.Sb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.MA,this),(0,g.x)(this.WM,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.NC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=xva,b=g.w("yt.mdx.remote.debug.handlers_");g.fb(b||[],a);g.me(this.o);D7.Gb.Y.call(this)};
g.h.Sb=function(a){i7("Controller",a)};
g.h.NA=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.vM=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Sb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Sb("Stopping receiver w/o session: "+a.friendlyName)}else this.Sb("onReceiverAction_ called without receiver.")};
g.h.PK=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Sb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.NF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.xr,b))};
g.h.MA=function(a){if(!this.la()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Sb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.ce(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.me(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.NA,this,this.o)),this.o.lj(null));this.o.Yt(a)}}};
g.h.EP=function(){return this.o?this.o.OC():null};
g.h.WM=function(a){this.la()||(this.Sb("Failed to estabilish a session: "+g.Kk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.zM=function(a){E7("Receiver availability updated: "+a);if(!this.la()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.NC=function(){this.la()||(this.w=Vva(this),E7("Updating custom receivers: "+g.Kk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.x)(function(){this.Sb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.DO;D7.prototype.setConnectedScreenStatus=D7.prototype.CO;D7.prototype.stopSession=D7.prototype.FP;D7.prototype.getCastSession=D7.prototype.EP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Sb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Sb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Ra(this.setVolume,a,b))};
g.h.NB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kk(b.style),g.gc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Ra(this.NB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.JC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Ra(this.JC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Ra(this.nextVideo,a,b))};
g.h.zw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.zw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.Y=function(){hwa(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.Y.call(this)};
g.h.Ku=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.cb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sM=function(a,b){this.R(a,b)};
g.h.wK=function(a){if(!a)this.Cl(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Cl=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),iwa(this),this.R("remotePlayerChange")};
g.h.vK=function(a){a?(iwa(this),this.R("remotePlayerChange")):this.Cl(null)};
g.h.HK=function(){var a=ewa();a&&Y7(this,a)};
g.h.Sb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Kk(l));this.o.connect({method:"setPlaylist",
params:g.Kk(l)},a,vua())}else g8("Connecting without params"),this.o.connect({},a,vua());kwa(this)};
g.h.dispose=function(){this.la()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.Jo(this.F);this.F=NaN;g.Jo(this.G);this.G=NaN;this.w=null;g.Gq(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.Y.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.dF=function(){this.Pi(2)};
g.h.AK=function(){g8("Channel opened");this.P&&(this.P=!1,j8(this),this.J=g.Ho((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Pi(1)},this),15E3));
zua(uva(this.o),this.S)};
g.h.xK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.yK=function(a){q6();isNaN(this.Ak())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.P=!0,g8("Channel error: "+a+" with reconnection in "+this.Ak()+" ms"),h8(this,2))};
g.h.zK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Kk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N6(a.params.devices);this.u=(0,g.A)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
nwa(this,a);break;case "loungeScreenDisconnected":g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
nwa(this,!1);break;case "remoteConnected":var b=new d6(N6(a.params.device));g.Za(this.u,function(c){return b?c.id==b.id:!1})||fua(this.u,b);
break;case "remoteDisconnected":b=new d6(N6(a.params.device));g.gb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":pwa(this,a);break;case "nowPlaying":rwa(this,a);break;case "onStateChange":qwa(this,a);break;case "onAdStateChange":swa(this,a);break;case "onVolumeChanged":twa(this,a);break;case "onSubtitlesTrackChanged":owa(this,a);break;case "nowAutoplaying":uwa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":vwa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.qO=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.SE=function(){var a=3;this.la()||(a=0,isNaN(this.Ak())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Pi=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();vva(this.o,a);this.dispose()};
g.h.RE=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.EO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.Jo(this.F),this.F=g.Ho((0,g.x)(this.qO,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.Kk(this.Sa.o)==g.Kk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.mx=function(){var a=this.o.C.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Ak=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.I)():NaN};
g.h.GE=function(){return this.A||"UNSUPPORTED"};
g.h.HE=function(){return this.C||""};
g.h.xP=function(){if(!isNaN(this.Ak())){var a=this.o.u;g.An(a.o);a.start()}};
g.h.zO=function(a,b){l8(this,a,b);mwa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.og;f8.prototype.getProxyState=f8.prototype.SE;f8.prototype.disconnect=f8.prototype.Pi;f8.prototype.getPlayerContextData=f8.prototype.RE;f8.prototype.setPlayerContextData=f8.prototype.EO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.mx;f8.prototype.getReconnectTimeout=f8.prototype.Ak;f8.prototype.getAutoplayMode=f8.prototype.GE;f8.prototype.getAutoplayVideoId=f8.prototype.HE;f8.prototype.reconnect=f8.prototype.xP;
f8.prototype.sendMessage=f8.prototype.zO;g.r(m8,m7);g.h=m8.prototype;g.h.ce=function(a){return this.qd.$_gs(a)};
g.h.contains=function(a){return!!this.qd.$_c(a)};
g.h.get=function(a){return this.qd.$_g(a)};
g.h.start=function(){this.qd.$_st()};
g.h.add=function(a,b,c){this.qd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.qd.$_r(a,b,c)};
g.h.zp=function(a,b,c,d){this.qd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.qd.$_ubk(this.u[a]);this.u.length=0;this.qd=null;m7.prototype.Y.call(this)};
g.h.BP=function(){this.R("screenChange")};
g.h.XL=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.CP;v7.prototype.$_gsppc=v7.prototype.MC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.zp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.ce;v7.prototype.$_gos=v7.prototype.LC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.og;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.B);g.h=G8.prototype;
g.h.Y=function(){g.B.prototype.Y.call(this);this.A.stop();this.C.stop();this.P.stop();this.U();this.o.unsubscribe("proxyStateChange",this.JA,this);this.o.unsubscribe("remotePlayerChange",this.Gl,this);this.o.unsubscribe("remoteQueueChange",this.Po,this);this.o.unsubscribe("autoplayUpNext",this.kA,this);this.o.unsubscribe("previousNextChange",this.GA,this);this.o.unsubscribe("nowAutoplaying",this.CA,this);this.o.unsubscribe("autoplayDismissed",this.jA,this);this.o=this.B=null};
g.h.jz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.xx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.uK=function(a){this.P.ZE(a)};
g.h.bP=function(a){this.jz("control_subtitles_set_track",g.ac(a)?null:a)};
g.h.aC=function(){var a=this.u.getOption("captions","track");g.ac(a)||K8(this,a)};
g.h.uA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Gl,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.Gl,this)}};
g.h.tL=function(){g.ac(this.F)||Hwa(this,this.F);this.G=!1};
g.h.JA=function(a,b){this.C.stop();2==b&&this.ZB()};
g.h.Gl=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.pD(8));this.YB();break;case 1085:case 3:I8(this,new g.pD(9));break;case 1083:case 0:I8(this,new g.pD(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.pD(4));break;case 2:I8(this,new g.pD(4));H8(this,V7(a));
break;case -1:I8(this,new g.pD(64));break;case -1E3:I8(this,new g.pD(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Hwa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.zC()}else Gwa(this)};
g.h.GA=function(){this.u.R("mdxpreviousnextchange")};
g.h.Po=function(){J8(this)||Gwa(this)};
g.h.XD=function(){this.o.zw()};
g.h.kA=function(){};
g.h.CA=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.jA=function(){this.u.R("mdxautoplaycanceled")};
g.h.WH=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.zC=function(){if(J8(this)){var a=$7(this.o);this.w.Wa(this.S);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.S=this.w.L(this.u,"onVolumeChange",this.uA)}};
g.h.YB=function(){this.A.stop();if(!this.o.la()){var a=$7(this.o);1==a.playerState&&I8(this,new g.pD(8));H8(this,V7(a));this.A.start()}};
g.h.ZB=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.V);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.V);N8.prototype.A=function(a){Jwa(this,a.state)};g.r(O8,g.BO);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.wb(a,this.B,this),g.DO(this,(0,g.A)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Ce(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Re=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.Zc=function(a){g.BO.prototype.Zc.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.nb()};g.r(P8,g.LP);g.h=P8.prototype;
g.h.create=function(){Awa(g.Ax(this.player.N()));this.A.push(g.Oo("yt-remote-before-disconnect",this.rK,this));this.A.push(g.Oo("yt-remote-connection-change",this.AM,this));this.A.push(g.Oo("yt-remote-receiver-availability-change",this.HA,this));this.A.push(g.Oo("yt-remote-auto-connect",this.yM,this));this.A.push(g.Oo("yt-remote-receiver-resumed",this.xM,this));this.A.push(g.Oo("mdx-privacy-popup-confirm",this.cO,this));this.A.push(g.Oo("mdx-privacy-popup-cancel",this.bO,this));this.HA()};
g.h.load=function(){this.player.cancelPlayback();g.LP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Fwa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));Iwa(this,this.F,this.F);g.tT(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.ne(this.B,this.o);this.o=this.B=null;g.LP.prototype.unload.call(this);g.tT(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Po(this.A);g.LP.prototype.Y.call(this)};
g.h.rl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.jz.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.UE=function(){return this.loaded?this.B.suggestion:null};
g.h.lf=function(){return this.o?$7(this.o).lf:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Pc():!a.isAdPlaying()&&this.player.Pc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.DH=function(){this.o&&this.o.JC()};
g.h.rK=function(a){1==a&&(this.S=this.o?$7(this.o):null)};
g.h.AM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.S=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.me(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.S)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.HA=function(){this.J=[this.u].concat(Cwa());var a=y8()||this.u;R8(this,a);this.player.ka("onMdxReceiversChange")};
g.h.SN=function(a){!this.P&&g.DD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.yM=function(){var a=y8();R8(this,a)};
g.h.xM=function(){this.w=y8()};
g.h.cO=function(){this.P=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.bO=function(){this.P=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Mc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.EH=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Bf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.$P.remote=P8;})(_yt_player);
